### ISSUE TITLE
Images from Kinect are in BGRD space, not RGBD as declared

### ISSUE THREAD

**Issue by hris2003** [plasmodic/ecto_image_pipeline#6]
I'm using ROS ORK_linemod for 3D object detection and notice that the color images retrieved from Kinect source are in BGR color space, not RGB space as written in ecto_image_pipeline code. 

However, if I run ORK_linemod from it's sample folder, color images are rendered correctly (i.e. in RGB space).

**Comment by stonier** [comment]
Duplicate of #2.
