### ISSUE TITLE
Error when calling create_source with OpenNISubscriber as 2nd argument

### ISSUE THREAD

**Issue by corot** [plasmodic/ecto_image_pipeline#7]
Hi, not sure if this is an issue at all, or I'm just trying to over abuse [camera_base](https://github.com/plasmodic/ecto_image_pipeline/blob/master/python/ecto_image_pipeline/io/source/camera_base.py). Feel free to close this if so!

I'm trying to run object_recognition_capture orb_template with a non OpenNI camera (see [this post](https://groups.google.com/forum/#!topic/object-recognition-kitchen/KiXsCxP_uMY) on ORK group), so I pass OpenNISubscriber to create_source instead of OpenNISource (and also remove the mask_depth from the outputs_list). But I get an error complaining that this is not a ROS node:
```
$ rosrun object_recognition_capture orb_template -o my_textured_plane
INIT
Listening for key: s on imshow:save
[FATAL] [1426455554.600357664]: You must call ros::init() before creating the first NodeHandle
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
[ERROR] [1426455554.601597709]: [registerPublisher] Failed to contact master at [:0].  Retrying...
Couldn't find an AF_INET address for []
Couldn't find an AF_INET address for []
......
```
I crudely tried to call rospy.init_node but changes nothing. So it's really a missing ros::init() in a C++ ecto cell?
Please note that I'm trying to use ORK in an undocumented way, so... it's probably that I'm just trying something stupid without understanding the ecto_image_pipeline.

**Comment by stonier** [comment]
Did you call something like:

```
ecto_ros.init(sys.argv, "my_node_name", anonymous=False)
```

from somewhere in your python script? This initialises the underlying c++ node.

**Comment by corot** [comment]
right.  danke!

Still doesn't work but now is opencv complaining about some incompatibilities between images.

**Comment by stonier** [comment]
You could be running into the same problem on ecto 0.6.8 as being hunted in https://github.com/plasmodic/ecto/issues/272. Get the [ecto](https://github.com/plasmodic/ecto) sources and checkout the 0.6.7 tag to make sure.

**Comment by corot** [comment]
mmm....   don't think so, as it works for the images provided by kinect (well... actually, it also fails but something different and later.
I'll try ecto sources, anyway. Thanks!
